### ISSUE TITLE
bbcpex_script_rebuilder.py produces "list index out of range" error

### ISSUE THREAD

**Issue by Labreezy** [dantarion/bbtools#2]
```
Traceback (most recent call last):
  File "bbcpex_script_rebuilder.py", line 237, in <module>
    rebuild_bbscript("static_db/bb/scr_rm.bin.py","test_rebuild/scr_rm.bin")
  File "bbcpex_script_rebuilder.py", line 226, in rebuild_bbscript
    Rebuilder().visit(sourceAST)
  File "C:\Python26\lib\site-packages\astor\misc.py", line 161, in visit
    return visitor(node)
  File "bbcpex_script_rebuilder.py", line 75, in visit_Module
    if function.decorator_list[0].id != "State":
IndexError: list index out of range
```

This was with a default,parsed char_rm_scr.bin, no changes made besides deleting an empty MatchInit2 and removing the first if statement in DriveVoice, both of which astor complained about when rebuilding.

If you would like the tracebacks for those i'd be happy to give them to you.

**Comment by dantarion** [comment]
Looks like its stuck on a function decorator, either @State or @Subroutine. Might need to reparse some of the original files as well. Empty If's and empty functions need a pass() inserted as the body of the block in order for them to be valid python syntax. The dumps on boxdox don't currently have that.

**Comment by dantarion** [comment]
I think you fixed this problem yourself, ill reopen if its still valid

**Comment by Labreezy** [comment]
Yeah, it's been fixed, just a version mismatch
